feat: ["**/*.go", "**/*.poml"]
fix: ["**/*.go"]
docs: ["docs/**", "**/*.md", "**/*.poml"]
ci: [".github/workflows/**"]
chore: ["package.json", ".releaserc.json"]
style: ["**/*.css", "**/*.scss", "**/*.html"]
refactor: ["**/*.go"]
test: ["**/*_test.go", "**/*.poml"]
perf: ["**/*.go"]